<section>
    <h2>Our Application</h2>
    <p>
        What we will be building together is our Training Center Application or TC for short. Our first module will be the Debug module. It will help us get a better understanding of the inner workings of our application. Then we will create a module called User tha will handle user management. Finally we will add an Exam module that will be responsible for listing and taking exames.
    </p>
    <p>
        With every new module we will demonstrate how the different ZF2 components can best be used to continuously improve our application.
    </p>
</section>